warn-unused-variables = true
unused-variable-pattern = "^_"
cognitive-complexity-threshold = 20
type-complexity-threshold = 250
too-many-arguments-threshold = 8
deny-missing-docs = true
deny-unsafe-code = true
deny-redundant-clone = true
deny-unnecessary-unwrap = true
deny-result-unwrap-used = true
deny-option-unwrap-used = true
