tab_spaces = 2
use_tabs = false
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
format_strings = true
format_macro_matchers = true
normalize_comments = true
wrap_comments = true
comment_width = 80
max_width = 100
trailing_semicolon = true
edition = "2021"
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
type_punctuation_density = "Wide"
control_brace_style = "AlwaysSameLine"
brace_style = "PreferSameLine"
