name: Publish

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  create-release-draft:
    name: Create Release Draft
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Automated release for version ${{ github.ref_name }}.
          draft: true
          prerelease: ${{ contains(github.ref_name, '-') }}

  build-tauri:
    name: Build Tauri App
    needs: create-release-draft
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: aarch64-apple-darwin
            args: --target aarch64-apple-darwin
          - platform: macos-latest
            target: x86_64-apple-darwin
            args: --target x86_64-apple-darwin
          - platform: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            args: ''
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            args: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Rust stable with targets
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install Linux dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile

      - name: Build and upload with Tauri Action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.create-release-draft.outputs.release_id }}
          tagName: ${{ github.ref_name }}
          args: ${{ matrix.args }}

  publish-release:
    name: Publish Release
    needs: [create-release-draft, build-tauri]
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release (remove draft status)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ needs.create-release-draft.outputs.release_id }},
              draft: false
            })
